DROP TABLE IF EXISTS t_authors_books;
DROP TABLE IF EXISTS t_authors;
DROP TABLE IF EXISTS t_books;

CREATE TABLE t_books
(
    book_id          bigint primary key generated by default as identity,
    title            varchar not null,
    isbn             varchar not null unique,
    num_pages        integer not null check ( num_pages >= 1 ),
    publication_date date    not null
);

CREATE TABLE t_authors
(
    author_id  bigint primary key generated by default as identity,
    name       varchar      not null,
    birth_date date         not null,
    country    varchar(100) not null
);

CREATE TABLE t_authors_books
(
    author_id bigint references t_authors (author_id) ON DELETE CASCADE,
    book_id   bigint references t_books (book_id) ON DELETE CASCADE,
    primary key (author_id, book_id)
);

INSERT INTO t_authors(name, birth_date, country)
VALUES ('Джон Рональд Руэл Толкин', '1892-01-03', 'Великобритания'),
       ('Джордж Рэймонд Ричард Мартин', '1948-09-20', 'США'),
       ('Пэтрик Ротфусс', '1973-06-06', 'США'),
       ('Роберт Джордан', '1948-10-17', '1948-10-17'),
       ('Терри Пратчетт', '1948-04-28', 'Великобритания'),
       ('Кристофер Толкин', '1924-11-21', 'Великобритания'),
       ('Лев Толстой', '1828-09-09', 'Россия'),
       ('Алексей Толстой', '1883-12-10', 'Россия');

INSERT INTO t_books (title, isbn, num_pages, publication_date)
VALUES ('Властелин колец: Братство кольца', '9780547928210', 432, '1954-07-29'),
       ('Хоббит, или Туда и обратно', '9780007458424', 400, '1937-09-21'),
       ('Игра престолов', '9780553103540', 694, '1996-08-01'),
       ('Буря мечей', '9780553106633', 976, '2000-11-08'),
       ('Имя ветра', '9781473211896', 662, '2007-04-10'),
       ('Мудрец-убийца', '9781473211933', 1008, '2011-03-01'),
       ('Колесо времени: Ветер полночи', '9780451456899', 708, '1990-01-15'),
       ('Колесо времени: Путь от дороги', '9780765339995', 352, '2020-10-06'),
       ('Удача первоклассника', '9781473200197', 288, '1983-12-02'),
       ('Цвет волшебства', '9781473200104', 288, '1983-12-02'),
       ('Сильмариллион', '9785477056154', 384, '1977-09-15'),
       ('Война и мир', '9785699578706', 1248, '1869-01-01');

INSERT INTO t_authors_books
VALUES (1, 1),
       (1, 2),
       (2, 3),
       (2, 4),
       (3, 5),
       (3, 6),
       (4, 7),
       (4, 8),
       (5, 9),
       (5, 10),
       (1, 11),
       (6, 11),
       (7, 12),
       (8, 12);